# Generated by Django 2.2.5 on 2020-07-03 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200703_1953'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='curreny',
            new_name='currency',
        ),
    ]
